"""Pinned and generated zones inside an automatically reconciled section body.

The laptop-wide reconciler rewrites its section files whenever the evidence
fingerprint changes, which silently destroyed anything a human or an agent had
written into them. This module splits a section body into the part the
reconciler owns (``generated``) and the part it must carry forward untouched
(``pinned``), so automation and authorship can share one file.

Pinned content is rendered *first*. The context compiler truncates from the end
of a body when it runs out of budget, so the user's own words must precede the
regenerated evidence to survive that cut.

Parsing is deliberately tolerant. Every existing machine has section files with
no markers at all, and those must keep working: a body with no markers is
treated as fully generated with an empty pinned zone, which makes the migration
a no-op on the next reconcile.
"""
from __future__ import annotations

import re
from dataclasses import dataclass

PINNED_OPEN = "<!-- docmancer:pinned -->"
PINNED_CLOSE = "<!-- /docmancer:pinned -->"
GENERATED_CLOSE = "<!-- /docmancer:generated -->"

# ``revision`` is informational: it tells a human reading the raw file which
# reconcile produced the block. It is not used to decide whether to regenerate
# (the evidence fingerprint in laptop.py owns that decision), so a missing or
# malformed revision attribute is not an error.
_GENERATED_OPEN_RE = re.compile(
    r"<!--\s*docmancer:generated(?P<attrs>[^>]*?)-->",
    re.IGNORECASE,
)
_PINNED_BLOCK_RE = re.compile(
    re.escape(PINNED_OPEN) + r"(?P<body>.*?)" + re.escape(PINNED_CLOSE),
    re.DOTALL | re.IGNORECASE,
)
_REVISION_RE = re.compile(r"revision=(?P<value>[A-Za-z0-9_.:-]+)")

# The banner is repeated in every section file, which makes its vocabulary
# corpus-ubiquitous and therefore worthless as a retrieval signal (see the
# Release 0 finding documented in docmancer/memory/tree/compiler.py). Worse, any
# word it *shares* with a real document is pushed toward zero IDF for every
# query. An earlier draft read "Generated by Docmancer ... docmancer memory
# canonical pin ...", which flattened "memory" and "canonical" across the whole
# corpus and knocked the self-description off the top of terminology queries.
#
# So the banner deliberately avoids every alias in laptop._SELF_DESCRIPTION_ALIASES
# and every product noun. It explains the rule positionally ("above this block")
# instead of naming a command; the command itself lives in the self-description
# entry, which is the one document that should rank for it.
# tests/test_zones.py::test_banner_avoids_retrieval_vocabulary enforces this.
BANNER_TEMPLATE = (
    "Lines below are rewritten automatically whenever the evidence changes, so "
    "edits there are lost. Notes written above this block are kept."
)


class ZoneViolation(ValueError):
    """A write would change the zone the reconciler owns.

    Carries a structured payload so an MCP client or CLI can recover without
    parsing prose. ``pin_hint`` names the call the caller should have made.
    """

    code = "generated_zone_readonly"

    def __init__(self, address: str, *, pin_hint: str) -> None:
        super().__init__(
            f"{address} has a Docmancer-generated zone that is rewritten on every "
            f"sync, so this edit would be lost. Write to the pinned zone instead: {pin_hint}"
        )
        self.address = address
        self.pin_hint = pin_hint

    def payload(self) -> dict:
        return {
            "ok": False,
            "error": self.code,
            "address": self.address,
            "message": str(self),
            "recovery": self.pin_hint,
        }


@dataclass(frozen=True)
class Zones:
    """One section body, split. ``has_markers`` distinguishes a genuinely empty
    pinned zone from a legacy file that has never been through zone rendering."""

    pinned: str
    generated: str
    generated_revision: str = ""
    has_markers: bool = False

    @property
    def pinned_lines(self) -> list[str]:
        return [line for line in self.pinned.splitlines() if line.strip()]


def split_zones(body: str) -> Zones:
    """Split a section body into its pinned and generated zones.

    A body with no markers is fully generated with an empty pinned zone. An
    unterminated or otherwise malformed generated marker is also treated as
    fully generated: refusing to parse would strand the file, and treating
    ambiguous content as generated is the safe direction. Treating it as
    *pinned* would freeze a section forever with no way for the user to see why.
    """
    text = body or ""
    pinned_parts: list[str] = []

    def _collect(match: re.Match) -> str:
        pinned_parts.append(match.group("body").strip("\n"))
        return ""

    remainder = _PINNED_BLOCK_RE.sub(_collect, text)
    had_pinned_markers = bool(pinned_parts)

    revision = ""
    generated = remainder
    open_match = _GENERATED_OPEN_RE.search(remainder)
    if open_match:
        attrs = _REVISION_RE.search(open_match.group("attrs") or "")
        revision = attrs.group("value") if attrs else ""
        after_open = remainder[open_match.end():]
        close_index = after_open.lower().find(GENERATED_CLOSE.lower())
        generated = after_open[:close_index] if close_index != -1 else after_open

    return Zones(
        pinned="\n".join(part for part in pinned_parts if part).strip("\n"),
        generated=generated.strip("\n"),
        generated_revision=revision,
        has_markers=had_pinned_markers or bool(open_match),
    )


def render_zones(
    *,
    pinned: str,
    generated: str,
    revision: str,
    section: str,
) -> str:
    """Render both zones into one section body.

    The pinned block is emitted even when empty so the file always shows a
    human where their own notes belong. The banner sits outside the generated
    markers so it reads as page furniture rather than as content, and so
    `split_zones` never returns it as part of the generated text.
    """
    banner = BANNER_TEMPLATE
    return "\n".join(
        [
            PINNED_OPEN,
            (pinned or "").strip("\n"),
            PINNED_CLOSE,
            "",
            banner,
            "",
            f"<!-- docmancer:generated revision={revision or 'pending'} do-not-edit -->",
            (generated or "").strip("\n"),
            GENERATED_CLOSE,
            "",
        ]
    )


def replace_pinned(body: str, pinned: str, *, section: str) -> str:
    """Return ``body`` with only its pinned zone replaced.

    Used by every pin write path so a caller can change the user's own notes
    without needing to reproduce the generated zone.
    """
    zones = split_zones(body)
    return render_zones(
        pinned=pinned,
        generated=zones.generated,
        revision=zones.generated_revision,
        section=section,
    )


def guard_zoned_write(existing_body: str, new_body: str, *, address: str) -> None:
    """Raise ``ZoneViolation`` for a whole-body write that rewrites generated text.

    Identifies a managed file by the markers already in its body rather than by
    a tag lookup, so it needs no agent, no index, and no knowledge of which
    sections exist. A file with no markers is not managed and is never guarded.
    """
    zones = split_zones(existing_body)
    if not zones.has_markers:
        return
    if generated_zone_changed(existing_body, new_body):
        section = address.removesuffix(".md").rsplit("/", 1)[-1]
        raise ZoneViolation(
            address,
            pin_hint=f'docmancer memory canonical pin {section} "your note"',
        )


def generated_zone_changed(before: str, after: str) -> bool:
    """True when ``after`` alters the zone the reconciler owns.

    Whitespace-only differences do not count: an editor that normalises a
    trailing newline must not read as an attempt to rewrite generated content.
    """
    left = split_zones(before)
    right = split_zones(after)
    return " ".join(left.generated.split()) != " ".join(right.generated.split())
